### PR TITLE
Initial Netatmo Welcome camera API

### PR DESCRIPTION
**Pull request by wep4you**
Implemented the welcome camera Api. Can you please generate a new Jar File, that i can implement it in the OpenHab2 netatmo binding.

Thanks

### CODE REVIEW

**Comment by cbornet** [comment]
Lots of work, thanks a lot !
Just a remark and then I'll merge this: can you replace POST by GET where it is possible ?
Because Netatmo don't set the headers for pre-flight CORS requests (http://forum.netatmo.com/viewtopic.php?f=5&t=4908), the POST requests fail on some browsers.

**Comment by cbornet** [comment]
Once this is merged, I'll add credits for you and @clinique in the README.
As for the OpenHAB binding, cc @clinique

**Comment by wep4you** [comment]
@cbornet Ok changed all from post to get and did some  more tests, so all should work

**Comment by wep4you** [comment]
@cbornet Wehn do you plan to merge this commit, i need the java skeleton for the implementation, and i can't build it on my own with netatmo-swagger-api because of errors. Thanks

**Comment by cbornet** [comment]
Thanks a lot for your contribution !

**Pull request merged**
