### PR TITLE
Update swagger.json to handle getstationsdata entrypoint

### PR DESCRIPTION
**Pull request by clinique**

### CODE REVIEW

**Comment by clinique** [comment]
Hello @cbornet , this time a properly formatted PR :)
I was also wondering wether we should or not remove obsolete functions from decl file now that we've got getstationsdata and getthermostatsdata.

**Comment by cbornet** [comment]
Your PR still wants to remove the latest commits ! (in info field). Can you update it ?
A guide I like to follow for submitting/updating PRs : https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request

As for obsolete functions I think they can be tagged as "Deprecated" so that they are isolated from the others.

**Comment by clinique** [comment]
Updated, thanks.

**Comment by cbornet** [comment]
Merged. Thanks !
I will try to update the generated code and see if I can add some unit tests to the retrofit2 sample (I got my hands on a weather station so now I can test).

**Comment by clinique** [comment]
If it can help, find [her](https://github.com/cbornet/netatmo-swagger-decl/files/313971/test.zip) the unit test extensions I made on my side

**Pull request merged**
